"""crear tabla consultorios

Revision ID: 08a0c78ba2ed
Revises: 77825bac6103
Create Date: 2026-10-06 23:19:52.021196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a0c78ba2ed'
down_revision = '77825bac6103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultorios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.VARCHAR(length=10), nullable=False),
    sa.Column('piso', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultorios')
    # ### end Alembic commands ###
