"""crear tabla medicos

Revision ID: 0c6e5de636b8
Revises: cc08209d873a
Create Date: 2026-10-02 00:57:36.592593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6e5de636b8'
down_revision = 'cc08209d873a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dni', sa.VARCHAR(length=20), nullable=False),
    sa.Column('colegiatura', sa.VARCHAR(length=20), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('apellido_paterno', sa.Text(), nullable=False),
    sa.Column('apellido_materno', sa.Text(), nullable=False),
    sa.Column('sexo', sa.Enum('M', 'F', name='sexopersona', create_type=False), nullable=False),
    sa.Column('telefono', sa.Text(), nullable=False),
    sa.Column('correo', sa.Text(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('Activo', 'Inactivo', 'De_Vacaciones', name='estadomedico'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('colegiatura'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('dni')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicos')
    # ### end Alembic commands ###
