"""creacion de las tablas de historial

Revision ID: 133a6b48667d
Revises: 1c309f270d40
Create Date: 2026-10-09 03:16:15.931577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133a6b48667d'
down_revision = '1c309f270d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historiales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cita_id', sa.UUID(), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('tratamiento', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cita_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historiales')
    # ### end Alembic commands ###
