"""crear tabla citas

Revision ID: 1c309f270d40
Revises: 08a0c78ba2ed
Create Date: 2026-10-07 00:06:35.892896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c309f270d40'
down_revision = '08a0c78ba2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('medico_id', sa.UUID(), nullable=False),
    sa.Column('consultorio_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('Confirmada', 'Atendida', 'Cancelada', name='estadocita'), nullable=False),
    sa.ForeignKeyConstraint(['consultorio_id'], ['consultorios.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citas')
    # ### end Alembic commands ###
