"""crear tabla usuarios

Revision ID: 3a15a03c4722
Revises: 1c309f270d40
Create Date: 2026-10-08 14:59:29.851048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a15a03c4722'
down_revision = '1c309f270d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=10), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('rol', sa.Enum('Admin', 'Recepcionista', 'Medico', name='rolusuario'), nullable=False),
    sa.Column('estado', sa.Enum('Activo', 'Inactivo', name='estadousuario'), nullable=False),
    sa.Column('medico_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medico_id'),
    sa.UniqueConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
