"""crear tabla especialidades

Revision ID: 456790413e7c
Revises: 0c6e5de636b8
Create Date: 2026-10-02 17:25:26.782512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456790413e7c'
down_revision = '0c6e5de636b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('especialidades')
    # ### end Alembic commands ###
