"""cambiar id de especialidades a UUID

Revision ID: 77825bac6103
Revises: 879fd072f3c1
Create Date: 2026-10-06 17:47:48.753228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77825bac6103'
down_revision = '879fd072f3c1'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('medicos_especialidades')
    op.drop_table('especialidades')

    op.create_table(
        'especialidades',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nombre', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nombre')
    )

    op.create_table(
        'medicos_especialidades',
        sa.Column('medico_id', sa.UUID(), nullable=False),
        sa.Column('especialidad_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['especialidad_id'], ['especialidades.id']),
        sa.ForeignKeyConstraint(['medico_id'], ['medicos.id']),
        sa.PrimaryKeyConstraint('medico_id', 'especialidad_id')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicos_especialidades', schema=None) as batch_op:
        batch_op.alter_column('especialidad_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('especialidades', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
