"""cambiar id de medicos a UUID

Revision ID: 879fd072f3c1
Revises: c95a0c2279ca
Create Date: 2026-10-06 17:07:12.998323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879fd072f3c1'
down_revision = 'c95a0c2279ca'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('medicos_especialidades')
    op.drop_table('medicos')

    op.create_table(
        'medicos',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('dni', sa.VARCHAR(20), nullable=False),
        sa.Column('colegiatura', sa.VARCHAR(20), nullable=False),
        sa.Column('nombre', sa.Text(), nullable=False),
        sa.Column('apellido_paterno', sa.Text(), nullable=False),
        sa.Column('apellido_materno', sa.Text(), nullable=False),
        sa.Column('sexo', sa.Enum('M', 'F', name='sexopersona', create_type=False), nullable=False),
        sa.Column('telefono', sa.Text(), nullable=False),
        sa.Column('correo', sa.Text(), nullable=False),
        sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
        sa.Column(
            'estado',
            sa.Enum('Activo', 'Inactivo', 'De Vacaciones', name='estadomedico', create_type=False),
            nullable=False
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('dni'),
        sa.UniqueConstraint('colegiatura'),
        sa.UniqueConstraint('correo')   
    )

    op.create_table(
        'medicos_especialidades',
        sa.Column('medico_id', sa.UUID(), nullable=False),
        sa.Column('especialidad_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['especialidad_id'], ['especialidades.id']),
        sa.ForeignKeyConstraint(['medico_id'], ['medicos.id']),
        sa.PrimaryKeyConstraint('medico_id', 'especialidad_id')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicos_especialidades', schema=None) as batch_op:
        batch_op.alter_column('medico_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('medicos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
