"""Cambiar id de pacientes a UUID

Revision ID: c95a0c2279ca
Revises: ebcfdd624be0
Create Date: 2026-10-06 12:43:36.091584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95a0c2279ca'
down_revision = 'ebcfdd624be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dni', sa.VARCHAR(length=20), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('apellido_paterno', sa.Text(), nullable=False),
    sa.Column('apellido_materno', sa.Text(), nullable=False),
    sa.Column('telefono', sa.Text(), nullable=False),
    sa.Column('correo', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.Enum('M', 'F', name='sexopersona', create_type=False), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('dni')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pacientes')
    # ### end Alembic commands ###
