"""crear tabla pacientes

Revision ID: cc08209d873a
Revises: 
Create Date: 2026-10-01 17:30:53.284791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc08209d873a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dni', sa.VARCHAR(length=20), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('apellido_paterno', sa.Text(), nullable=False),
    sa.Column('apellido_materno', sa.Text(), nullable=False),
    sa.Column('telefono', sa.Text(), nullable=False),
    sa.Column('correo', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.Enum('M', 'F', name='sexopersona'), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('dni')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pacientes')
    # ### end Alembic commands ###
